name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Import GPG key
        run: |
          echo "$SIGNING_KEY" | gpg --batch --import
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Publish to Maven Central
        run: |
          PUBLISH_VERSION=${{ github.event.release.tag_name }} ./mill -i --ticker false \
            mill.scalalib.SonatypeCentralPublishModule/publishAll \
            --gpgArgs --passphrase="$GPG_PW",--batch,--yes,-a,-b,--pinentry-mode,loopback \
            --username "$SONATYPE_NAME" --password "$SONATYPE_PW" \
            --shouldRelease true
        env:
          GPG_PW: ${{ secrets.GPG_PW }}
          SONATYPE_NAME: ${{ vars.SONATYPE_NAME }}
          SONATYPE_PW: ${{ secrets.SONATYPE_PW }}
