name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Mill dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/mill
            ~/.ivy2/cache
            ~/.cache/coursier
          key: ${{ runner.os }}-mill-${{ hashFiles('build.sc') }}
          restore-keys: |
            ${{ runner.os }}-mill-

      - name: Import GPG key
        run: |
          echo "$SIGNING_KEY" | gpg --import
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Publish to Maven Central
        run: |
          PUBLISH_VERSION=${{ github.ref_name }} ./mill -i --disable-ticker \
            mill.scalalib.PublishModule/publishAll \
            --gpgArgs --passphrase=$GPG_PW,--batch,--yes,-a,-b \
            --sonatypeCreds $SONATYPE_NAME:$SONATYPE_PW \
            --publishArtifacts __.publishArtifacts \
            --release true
        env:
          GPG_PW: ${{ secrets.GPG_PW }}
          SONATYPE_NAME: ${{ secrets.SONATYPE_NAME }}
          SONATYPE_PW: ${{ secrets.SONATYPE_PW }}
